" Vim syntax file for Bullang (.bu)
" Language: Bullang
" Maintainer: The Bullang Foundation
" Generated by bullarchy editor-setup

if exists("b:current_syntax")
  finish
endif

" ── Comments ──────────────────────────────────────────────────────────────────
syn match bullangComment "//.*$"

" ── Directives ────────────────────────────────────────────────────────────────
syn match bullangDirective "#\(rank\|lang\|lib\|use\)"

" ── Rank values ───────────────────────────────────────────────────────────────
syn keyword bullangRank war theater battle strategy tactic skirmish

" ── Keywords ──────────────────────────────────────────────────────────────────
syn keyword bullangKeyword let struct enum blueprint native

" ── Booleans ──────────────────────────────────────────────────────────────────
syn keyword bullangBoolean true false

" ── Primitive types ───────────────────────────────────────────────────────────
" Bullang's type system is deliberately small — see the language README.
syn keyword bullangType i32 i64 f64 bool String
syn keyword bullangType Tuple

" ── Native blocks ─────────────────────────────────────────────────────────────
syn region bullangNative
  \ start="@\(rust\|python\|c\|cpp\|go\|java\)\b"
  \ end="@end\b"
  \ contains=bullangNativeDelim

syn match bullangNativeDelim "@\(rust\|python\|c\|cpp\|go\|java\|end\)\b"
  \ contained

" ── builtin:: calls ───────────────────────────────────────────────────────────
syn match bullangBuiltinNs "builtin::"
syn match bullangBuiltinFn "builtin::\zs[a-z_][a-z_0-9]*\b"

" ── Enum variants (Type::Variant) ─────────────────────────────────────────────
syn match bullangEnumType "\b[A-Z][a-zA-Z0-9_]*\ze::"
syn match bullangEnumVariant "::\zs[A-Z][a-zA-Z0-9_]*\b"

" ── Function name in declaration ──────────────────────────────────────────────
syn match bullangFuncName "\(\blet\s\+\)\@<=[a-z_][a-zA-Z0-9_]*\ze\s*\((<[^>]*>)\)\?\s*("

" ── Parameter: name : Type ────────────────────────────────────────────────────
syn match bullangParam "\b[a-z_][a-zA-Z0-9_]*\ze\s*:"

" ── Pipe arrow ────────────────────────────────────────────────────────────────
syn match bullangArrow "->"

" ── Bindings {var} ────────────────────────────────────────────────────────────
syn match bullangBinding "{[a-z_][a-zA-Z0-9_]*}"

" ── Strings with interpolation ────────────────────────────────────────────────
syn region bullangString start='"' end='"' skip='\\"'
  \ contains=bullangInterp,bullangEscape

syn match bullangInterp "{[a-z_][a-zA-Z0-9_]*}" contained
syn match bullangEscape "\\." contained

" ── Numbers ───────────────────────────────────────────────────────────────────
syn match bullangNumber "\b[0-9][0-9_]*\(\.[0-9][0-9_]*\)\?\b"

" ── Operators ─────────────────────────────────────────────────────────────────
syn match bullangOperator "==\|!=\|<=\|>=\|&&\|||!\|[+\-*/%<>]"

" ── User-defined types (PascalCase) ───────────────────────────────────────────
syn match bullangUserType "\b[A-Z][a-zA-Z0-9_]*\b"

" ── Highlight links ───────────────────────────────────────────────────────────
" Rust-inspired:
hi def link bullangFuncName      Function
hi def link bullangParam         Identifier
hi def link bullangType          Type
hi def link bullangUserType      Type
hi def link bullangEnumType      Type
hi def link bullangEnumVariant   Constant
hi def link bullangNumber        Number
hi def link bullangOperator      Operator
hi def link bullangArrow         Operator

" Python-inspired:
hi def link bullangKeyword       Keyword
hi def link bullangBoolean       Boolean
hi def link bullangDirective     PreProc
hi def link bullangRank          StorageClass
hi def link bullangComment       Comment
hi def link bullangString        String
hi def link bullangEscape        SpecialChar
hi def link bullangInterp        Special

" Bullang-specific:
hi def link bullangBuiltinNs     Special
hi def link bullangBuiltinFn     Function
hi def link bullangBinding       Special
hi def link bullangNativeDelim   WarningMsg
hi def link bullangNative        Comment

let b:current_syntax = "bullang"
