" Vim syntax file for Bullang (.bu)
" Language: Bullang
" Maintainer: The Bullang Foundation
" Generated by bullarchy editor-setup

if exists("b:current_syntax")
  finish
endif

" ── Comments ──────────────────────────────────────────────────────────────────
syn match bullangComment "//.*$"

" ── Directives ────────────────────────────────────────────────────────────────
syn match bullangDirective "#\(rank\|lang\|lib\|use\)"

" ── Rank values ───────────────────────────────────────────────────────────────
syn keyword bullangRank war theater battle strategy tactic skirmish

" ── Keywords ──────────────────────────────────────────────────────────────────
" `blueprint` and `native` were never Bullang keywords — a blueprint is a file
" passed to `bullarchy init`, and an escape block opens with @<backend>.
syn keyword bullangKeyword let struct enum

" ── Booleans ──────────────────────────────────────────────────────────────────
syn keyword bullangBoolean true false

" ── Primitive types ───────────────────────────────────────────────────────────
" Bullang's type system is deliberately small — see the language README.
" Every type Bullang has. i32 was never one of them.
syn keyword bullangType i64 f64 bool String
syn keyword bullangType Tuple

" ── Native blocks ─────────────────────────────────────────────────────────────
syn region bullangNative
  \ start="@\(rust\|python\|c\|cpp\|go\|java\)\b"
  \ end="@end\b"
  \ contains=bullangNativeDelim

syn match bullangNativeDelim "@\(rust\|python\|c\|cpp\|go\|java\|end\)\b"
  \ contained

" ── builtin:: calls ───────────────────────────────────────────────────────────
syn match bullangBuiltinNs "builtin::"
" Known builtins, from `bullarchy stdlib`; anything else is flagged, which is
" the same distinction the VS Code grammar and the tree-sitter queries make.
syn keyword bullangBuiltinFn contained argc args close ends_with env exit
      \ i64_to_str in len max min open out replace_str run sleep starts_with
      \ str_to_i64 swap tern time to_lower to_upper trim
syn match bullangBuiltinBad "builtin::\zs[a-z_][a-z_0-9]*\>"
      \ contains=bullangBuiltinFn

" ── Enum variants (Type::Variant) ─────────────────────────────────────────────
" An enum variant is Type.Variant — `::` belongs to builtin:: alone.
syn match bullangEnumType "\<[A-Z][a-zA-Z0-9_]*\ze\.[A-Z]"
syn match bullangEnumVariant "::\zs[A-Z][a-zA-Z0-9_]*\b"

" ── Function name in declaration ──────────────────────────────────────────────
syn match bullangFuncName "\(\blet\s\+\)\@<=[a-z_][a-zA-Z0-9_]*\ze\s*\((<[^>]*>)\)\?\s*("

" ── Parameter: name : Type ────────────────────────────────────────────────────
syn match bullangParam "\b[a-z_][a-zA-Z0-9_]*\ze\s*:"

" ── Pipe arrow ────────────────────────────────────────────────────────────────
syn match bullangArrow "->"

" ── Bindings {var} ────────────────────────────────────────────────────────────
syn match bullangBinding "{[a-z_][a-zA-Z0-9_]*}"

" ── Strings with interpolation ────────────────────────────────────────────────
syn region bullangString start='"' end='"' skip='\\"'
  \ contains=bullangInterp,bullangEscape

syn match bullangInterp "{[a-z_][a-zA-Z0-9_]*}" contained
syn match bullangEscape "\\." contained

" ── Numbers ───────────────────────────────────────────────────────────────────
syn match bullangNumber "\b[0-9][0-9_]*\(\.[0-9][0-9_]*\)\?\b"

" ── Operators ─────────────────────────────────────────────────────────────────
syn match bullangOperator "==\|!=\|<=\|>=\|&&\|||!\|[+\-*/%<>]"

" ── User-defined types (PascalCase) ───────────────────────────────────────────
syn match bullangUserType "\b[A-Z][a-zA-Z0-9_]*\b"

" ── Highlight links ───────────────────────────────────────────────────────────
" Rust-inspired:
hi def link bullangFuncName      Function
hi def link bullangParam         Identifier
hi def link bullangBuiltinBad    Error
hi def link bullangType          Type
hi def link bullangUserType      Type
hi def link bullangEnumType      Type
hi def link bullangEnumVariant   Constant
hi def link bullangNumber        Number
hi def link bullangOperator      Operator
hi def link bullangArrow         Operator

" Python-inspired:
hi def link bullangKeyword       Keyword
hi def link bullangBoolean       Boolean
hi def link bullangDirective     PreProc
hi def link bullangRank          StorageClass
hi def link bullangComment       Comment
hi def link bullangString        String
hi def link bullangEscape        SpecialChar
hi def link bullangInterp        Special

" Bullang-specific:
hi def link bullangBuiltinNs     Special
hi def link bullangBuiltinFn     Function
hi def link bullangBinding       Special
hi def link bullangNativeDelim   WarningMsg
hi def link bullangNative        Comment

let b:current_syntax = "bullang"
