//! `bullarchy editor-setup` — writes LSP configuration for detected editors.
//!
//! Resolves the absolute path of the `bullarchy` binary for LSP configs.
//!
//! The server is `bullarchy lsp`. Every config written here used to name
//! `bullang lsp`, which is not a subcommand `bullang` has — `bullang` does
//! `stdlib` and nothing else. So every editor this command configured was
//! pointed at a process that exits immediately with "unrecognized subcommand",
//! and no editor reported anything more useful than the server having died.

const BULLANG_VIM_SYNTAX_URL: &str =
    "https://raw.githubusercontent.com/The-Bullang-Foundation/Bullang/main/vim/syntax/bullang.vim";

pub fn cmd_editor_setup() {
    use std::io::Write;
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    let mut configured = 0usize;
    let mut skipped    = 0usize;

    // The LSP server lives in bullarchy. Falls back to the bare name, which
    // relies on PATH, if resolution fails.
    let bin = which_bullarchy().unwrap_or_else(|| "bullarchy".to_string());
    // BullScript has its own server, `bullscript lsp`, for `.busc` files. It is
    // a separate binary from a separate repository, so it may well be absent —
    // in which case the editors are configured for `.bu` only rather than for
    // a command that is not there.
    let bs_bin = which_binary("bullscript");

    println!("bullarchy editor-setup");
    println!("  bullang  (.bu)   : {} lsp", bin);
    match &bs_bin {
        Some(b) => println!("  bullscript (.busc): {} lsp", b),
        None    => println!("  bullscript (.busc): not installed \u{2014} .busc left unconfigured"),
    }
    println!();

    // ── Neovim ───────────────────────────────────────────────────────────────
    let nvim_dir = std::path::PathBuf::from(&home).join(".config").join("nvim");
    if nvim_dir.exists() {
        let ftdetect = nvim_dir.join("after").join("ftdetect");
        std::fs::create_dir_all(&ftdetect).ok();
        let ftfile = ftdetect.join("bullang.vim");
        if !ftfile.exists() {
            let _ = std::fs::write(&ftfile,
                "au BufRead,BufNewFile *.bu set filetype=bullang\n");
            println!("  [Neovim] wrote {}", ftfile.display());
            configured += 1;
        } else {
            println!("  [Neovim] {} exists \u{2014} skipped", ftfile.display());
            skipped += 1;
        }

        let plugin_dir = nvim_dir.join("after").join("plugin");
        std::fs::create_dir_all(&plugin_dir).ok();
        let lua_file = plugin_dir.join("bullang.lua");
        if !lua_file.exists() {
            let lua = format!(
                "-- Bullang LSP (auto-generated by `bullarchy editor-setup`)\n\
                local ok, lspconfig = pcall(require, \"lspconfig\")\n\
                if not ok then return end\n\
                local configs = require(\"lspconfig.configs\")\n\
                if not configs.bullang then\n\
                  configs.bullang = {{\n\
                    default_config = {{\n\
                      cmd = {{ \"{bin}\", \"lsp\" }},\n\
                      filetypes = {{ \"bullang\" }},\n\
                      root_dir = lspconfig.util.root_pattern(\"inventory.bu\"),\n\
                    }},\n\
                  }}\n\
                end\n\
                lspconfig.bullang.setup({{}})\n",
                bin = bin
            );
            let _ = std::fs::write(&lua_file, &lua);
            println!("  [Neovim] wrote {}", lua_file.display());
            println!("           (requires nvim-lspconfig)");
            configured += 1;
        } else {
            println!("  [Neovim] {} exists \u{2014} skipped", lua_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Neovim] not detected (~/.config/nvim not found)");
    }
    println!();


    // ── Vim (ALE) ────────────────────────────────────────────────────────────
    let vim_dir = std::path::PathBuf::from(&home).join(".vim");
    if vim_dir.exists() {
        let ftdetect = vim_dir.join("ftdetect");
        std::fs::create_dir_all(&ftdetect).ok();
        let ftfile = ftdetect.join("bullang.vim");
        if !ftfile.exists() {
            let _ = std::fs::write(&ftfile,
                "au BufRead,BufNewFile *.bu set filetype=bullang\n");
            println!("  [Vim] wrote {}", ftfile.display());
            configured += 1;
        } else {
            println!("  [Vim] {} exists \u{2014} skipped", ftfile.display());
            skipped += 1;
        }
        // Write syntax file — fetched from Bullang repo, zero Vim plugin dependency
        let syntax_dir = vim_dir.join("syntax");
        std::fs::create_dir_all(&syntax_dir).ok();
        let syntax_file = syntax_dir.join("bullang.vim");
        if !syntax_file.exists() {
            let syntax_content = fetch_url(BULLANG_VIM_SYNTAX_URL);
            match syntax_content {
                Some(src) => {
                    let _ = std::fs::write(&syntax_file, &src);
                    println!("  [Vim] wrote {}", syntax_file.display());
                    configured += 1;
                }
                None => {
                    eprintln!("  [Vim] could not fetch syntax file from GitHub — check your internet connection.");
                    eprintln!("        URL: {}", BULLANG_VIM_SYNTAX_URL);
                }
            }
        } else {
            println!("  [Vim] {} exists \u{2014} skipped", syntax_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Vim] not detected (~/.vim not found)");
    }
    println!();

    // ── Helix ────────────────────────────────────────────────────────────────
    let helix_dir = std::path::PathBuf::from(&home).join(".config").join("helix");
    if helix_dir.exists() {
        let lang_file = helix_dir.join("languages.toml");
        let existing  = std::fs::read_to_string(&lang_file).unwrap_or_default();
        if existing.contains(r#"name = "bullang""#) {
            println!("  [Helix] bullang already in languages.toml \u{2014} skipped");
            skipped += 1;
        } else {
            let entry = format!(
                "\n[[language]]\n\
                name = \"bullang\"\n\
                scope = \"source.bullang\"\n\
                file-types = [\"bu\"]\n\
                comment-token = \"//\"\n\
                language-servers = [\"bullang-lsp\"]\n\
                \n\
                [language-server.bullang-lsp]\n\
                command = \"{bin}\"\n\
                args = [\"lsp\"]\n{bs}",
                bin = bin,
                bs = match &bs_bin {
                    Some(b) => format!(
                        "\n[[language]]\n\
                         name = \"bullscript\"\n\
                         scope = \"source.bullscript\"\n\
                         file-types = [\"busc\"]\n\
                         comment-token = \"//\"\n\
                         language-servers = [\"bullscript-lsp\"]\n\
                         \n\
                         [language-server.bullscript-lsp]\n\
                         command = \"{b}\"\n\
                         args = [\"lsp\"]\n",
                        b = b
                    ),
                    None => String::new(),
                }
            );
            let mut f = std::fs::OpenOptions::new()
                .create(true).append(true).open(&lang_file)
                .expect("cannot open languages.toml");
            let _ = f.write_all(entry.as_bytes());
            println!("  [Helix] appended to {}", lang_file.display());
            configured += 1;
        }
    } else {
        println!("  [Helix] not detected (~/.config/helix not found)");
    }
    println!();

    // ── Emacs (eglot) ────────────────────────────────────────────────────────
    let emacs_dir = std::path::PathBuf::from(&home).join(".emacs.d");
    if emacs_dir.exists() {
        let el_file = emacs_dir.join("bullang-lsp.el");
        if !el_file.exists() {
            let el = format!(
                ";; Bullang LSP (auto-generated by `bullarchy editor-setup`)\n\
                ;; Add to init.el: (load (expand-file-name \"bullang-lsp.el\" user-emacs-directory))\n\
                (require 'eglot)\n\
                (add-to-list 'auto-mode-alist '(\"\\\\.bu\\\\'\" . prog-mode))\n\
                (add-to-list 'eglot-server-programs\n\
                             '(prog-mode . (\"{bin}\" \"lsp\")))\n\
                (add-hook 'prog-mode-hook\n\
                          (lambda ()\n\
                            (when (and buffer-file-name\n\
                                       (string-suffix-p \".bu\" buffer-file-name))\n\
                              (eglot-ensure))))\n",
                bin = bin
            );
            let _ = std::fs::write(&el_file, &el);
            println!("  [Emacs] wrote {}", el_file.display());
            println!(r#"          add to init.el: (load (expand-file-name "bullang-lsp.el" user-emacs-directory))"#);
            configured += 1;
        } else {
            println!("  [Emacs] {} exists \u{2014} skipped", el_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Emacs] not detected (~/.emacs.d not found)");
    }
    println!();

    // ── Zed ──────────────────────────────────────────────────────────────────
    //
    // Zed is the one editor here that cannot be configured by writing a file.
    // Neovim, Vim, Helix and Emacs all accept "run this command for this file
    // type" as configuration. Zed will not recognise a new language at all
    // without an extension — a Rust crate compiled to WebAssembly, naming a
    // tree-sitter grammar — so there is nothing this command can append to
    // settings.json that would work.
    //
    // What it can do is set the file association, so `.bu` files at least open
    // as Bullang once the extension is installed, and say where the extension
    // is.
    let zed_dir = std::path::PathBuf::from(&home).join(".config").join("zed");
    if zed_dir.exists() {
        println!("  [Zed] detected ({})", zed_dir.display());
        println!("        Zed needs an extension, not a config entry — install it with:");
        println!("          zed: install dev extension   →  Bullang/zed-bullang");
        println!("        or from the extension registry once published.");
        println!("        It runs `{} lsp`, found on your PATH.", bin);
        if bs_bin.is_some() {
            println!("        For .busc files, install Bullscript/zed-bullscript as well.");
        }
    } else {
        println!("  [Zed] not detected (~/.config/zed not found)");
    }
    println!();

    // ── VS Code ───────────────────────────────────────────────────────────────
    println!("  [VS Code] install the extension (.vsix) from:");
    println!("            https://github.com/The-Bullang-Foundation/Bullang/releases");
    println!("            The extension will use the bullarchy binary at: {}", bin);
    println!();
    println!("configured: {}   skipped (already set up): {}", configured, skipped);
    if configured > 0 {
        println!();
        println!("binary path embedded: {}", bin);
        println!("if you move or reinstall bullarchy, re-run `bullarchy editor-setup`");
        println!("(delete the generated files first so they are regenerated)");
    }
}

// ── Helper: fetch URL content ─────────────────────────────────────────────────

fn fetch_url(url: &str) -> Option<String> {
    crate::utils::fetch_url(url)
}

// ── Helper: locate the bullang binary ────────────────────────────────────────

fn which_bullarchy() -> Option<String> {
    which_binary("bullarchy")
}

/// Resolve the absolute path of a binary via PATH.
///
/// `which` does not exist on Windows, where the equivalent is `where`.
fn which_binary(name: &str) -> Option<String> {
    let finder = if cfg!(windows) { "where" } else { "which" };
    let output = std::process::Command::new(finder)
        .arg(name)
        .output()
        .ok()?;
    if output.status.success() {
        let out = String::from_utf8(output.stdout).ok()?;
        // `where` can return several matches, one per line.
        Some(out.lines().next()?.trim().to_string())
    } else {
        None
    }
}
