//! README generation: written on `bullang init`, deleted on `bullang convert`.

use std::path::Path;

pub fn write_project_readme(project_root: &Path) {
    let path = project_root.join("README.md");
    match std::fs::write(&path, bullang_readme()) {
        Ok(_)  => println!("  wrote README.md (delete after reading — removed automatically on convert)"),
        Err(e) => eprintln!("warning: could not write README.md: {}", e),
    }
}

pub fn delete_project_readme(project_root: &Path) {
    let path = project_root.join("README.md");
    if path.exists() {
        if let Err(e) = std::fs::remove_file(&path) {
            eprintln!("warning: could not remove README.md: {}", e);
        }
    }
}

pub fn bullang_readme() -> &'static str {
r#"# Bullang — Quick-start README

> This file was generated by `bullang init` and is **automatically deleted** when
> you run `bullang convert`. Keep it as a reference while you write your project,
> then let the converter clean it up.

---

## What is Bullang?

Bullang (`.bu`) is a structured transpiler language. You write plain, typed
source files in a military-themed folder hierarchy, and `bullang convert`
produces clean, compilable code in your target language (Rust, Python, C, C++,
or Go).

Two core principles: **hierarchy first, then code** — and **invisible tooling**,
meaning the generated output has no trace of Bullang in it.

---

## Folder hierarchy

| Rank       | Depth | Role                              |
|------------|-------|-----------------------------------|
| `skirmish` | 1     | Leaf module — holds source files  |
| `tactic`   | 2     | Groups several skirmishes         |
| `strategy` | 3     | Groups several tactics            |
| `battle`   | 4     | Groups several strategies         |
| `theater`  | 5     | Groups several battles            |
| `war`      | 6     | Top-level root of a large project |

Every folder must contain an `inventory.bu`. Each rank may contain at most
5 sub-folders, 5 source files, 5 functions per file, and 5 bullets per function.

**Flow-downward rule:** functions and structs defined in a child folder are
available to its parent. You cannot call upward or sideways.

---

## The inventory file

Every folder has an `inventory.bu` that describes it entirely:

```
#rank: skirmish;
#lang: rs;
#lib: stdio.h;

struct Vec2 {
    x : f32,
    y : f32,
}

math : add_vec, dot_product;
```

### Directives

| Directive | Meaning                                     |
|-----------|---------------------------------------------|
| `#rank:`  | Rank of this folder (required)              |
| `#lang:`  | Target language: `rs` `py` `c` `cpp` `go`   |
| `#lib:`   | C/C++ header to include (repeatable)        |

`#lang:` set on a parent folder propagates to all descendants. A child
declaring a different `#lang:` than its parent is a validation error.

### Struct definitions

Structs are declared in `inventory.bu` only — never in source files. This
ensures they are emitted into the header or declaration layer of the output
(`.h`, `.hpp`, `lib.rs`, `__init__.py`, `types.go`), not into implementation
files.

The rank rule applies to structs too: a struct from a child inventory can be
used in that child's source files and in the parent's inventory and source
files. Never from a sibling or ancestor.

```
// tactic/inventory.bu
#rank: tactic;

struct Transform {
    position : Vec2,   // Vec2 declared in the child skirmish -- valid
    scale    : f32,
}

physics : apply_transform;
```

### Source file entries

After directives and structs, list every source file and its functions:

```
filename : fn1, fn2, fn3;
```

The validator cross-checks both directions: missing entries and undeclared
functions are both errors.

---

## Source files

Source files contain **only function declarations**.

```
let add(a: i32, b: i32) -> result: i32 {
    (a, b) : a + b -> {result};
}

let scale_and_add(x: i32, y: i32, factor: i32) -> result: i32 {
    (x, factor) : x * factor -> {scaled};
    (scaled, y) : scaled + y -> {result};
}
```

Pipe syntax: `(inputs) : expression -> {binding};`

The input list may be empty when the expression uses only literals or
interpolation:

```
let greet(name: String) -> result: String {
    () : "Hello {name}!" -> {result};
}
```

Rules:
- Every binding must be consumed by a later bullet, except the final output.
- The last bullet must bind to the declared output name.
- No binding may be assigned twice.
- Maximum 5 bullets per function, 5 functions per file.

---

## Types

| Bullang type    | Rust           | Python          | Go              | C               | C++                       |
|-----------------|----------------|-----------------|-----------------|-----------------|---------------------------|
| `i32`, `i64`    | `i32`/`i64`    | `int`           | `int32`/`int64` | `int32_t`       | `int32_t`                 |
| `f64`           | `f64`          | `float`         | `float64`       | `double`        | `double`                  |
| `String`        | `String`       | `str`           | `string`        | `char *`        | `std::string`             |
| `bool`          | `bool`         | `bool`          | `bool`          | `bool`          | `bool`                    |
| `Vec[T]`        | `Vec<T>`       | `list`          | `[]T`           | `vec_t` (1)     | `std::vector<T>`          |
| `HashMap[K, V]` | `HashMap<K,V>` | `dict`          | `map[K]V`       | `map_t` (1)     | `std::unordered_map<K,V>` |
| `Option[T]`     | `Option<T>`    | `Optional[T]`   | `*T`            | `T*`            | `std::optional<T>`        |
| `Result[T, E]`  | `Result<T,E>`  | n/a             | n/a             | n/a             | n/a                       |
| `Tuple[T, U]`   | `(T, U)`       | `tuple`         | `Tuple_T_U` (2) | N/A             | `std::tuple<T, U>`        |
| `UserStruct`    | `pub struct`   | `@dataclass`    | `struct`        | `typedef struct`| `struct`                  |

(1) C projects using `Vec[T]` or `HashMap[K,V]` get a `foreign_types.h`
emitted automatically. `map_t` uses string keys only.

(2) Go has no built-in tuple type. Bullang emits a named struct per unique
tuple combination into `types.go` — e.g. `Tuple[i32, f64]` becomes
`Tuple_i32_f64` with fields `V0 int32` and `V1 float64`.

---

## Expressions and operators

```
// Arithmetic
(a, b) : a + b -> {result};
(x, y) : x * y -> {product};

// Comparison (returns bool)
(a, b) : a == b -> {equal};
(x)    : x > 0.0 -> {positive};

// Integer and float literals
() : 42 -> {n};
() : 3.14 -> {pi};

// String interpolation
() : "value is {x}" -> {msg};

// Function call
(items) : sum(items) -> {total};
```

Supported operators: `+` `-` `*` `/` `%` `==` `!=` `<` `>` `<=` `>=`

---

## Error propagation (?)

Add `?` after a bullet's binding to propagate `None` or `Err` early. Only
valid when the function's output type is `Option[T]` or `Result[T, E]`.
Cannot appear on the last bullet.

```
let safe_root(x: f64) -> result: Option[f64] {
    (x) : x >= 0.0 -> {valid}?;
    @rust
    Some(x.sqrt())
    @end
}
```

The binding after `?` holds the unwrapped inner type (`T` from `Option[T]`).
Each backend emits the appropriate early-exit check (`expr?` in Rust,
`if x is None: return None` in Python, `if x == nil { return nil }` in Go,
`if (!x) { return NULL; }` in C, `if (!x) { return std::nullopt; }` in C++).

---

## Native escape blocks

When pipe syntax cannot express what you need, drop into the target language:

```
let sum_slice(values: Vec[i32]) -> result: i32 {
    @rust
    values.iter().sum()
    @end
}
```

Supported: `@rust`  `@python`  `@c`  `@cpp`  `@go`

A single function can carry one block per backend. Each conversion picks only
the matching block:

```
let native_greet(name: String) -> result: String {
    @rust
    format!("Hello, {}!", name)
    @end
    @python
    result = f"Hello, {name}!"
    @end
    @go
    return "Hello, " + name + "!"
    @end
}
```

**Restriction:** every native block must match the folder's `#lang:`. A
`@python` block in a `#lang: rs` folder is a validation error. `@c` is
accepted in `#lang: cpp` folders.

---

## Standard library (builtin::)

```
let absolute(x: i32) -> result: i32 {
    builtin::abs
}
```

| Category   | Builtins                                                                                       |
|------------|------------------------------------------------------------------------------------------------|
| Math       | `abs` `pow` `powf` `sqrt` `clamp` `min` `max` `log` `exp`                                     |
| Conditions | `tern`                                                                                         |
| String     | `to_upper` `to_lower` `trim` `starts_with` `ends_with` `replace_str` `to_string` `parse_i64` `len` |
| Algorithms | `swap` `insertion_sort` `quick_sort` `merge_sort` `radix_sort`                                 |
| I/O        | `in` `out` `open` `close` `time`                                                               |
| System     | `args` `exit` `env` `sleep`                                                                    |

Run `bullang stdlib --list` for full signatures and descriptions.

---

## Multi-language projects

A project can target different languages in different folders. Declare the
language per folder in the blueprint using a language prefix:

```
war my_project {
    theater engine {
        battle core {}
    }
    python: theater pipeline {
        battle data {}
    }
}
```

The language propagates to all descendants. Converting without `-e` converts
each language boundary independently to `_foldername` next to the source:

```sh
bullang convert my_project       # engine -> rs, pipeline -> py
bullang convert my_project -e rs # ERROR: project uses multiple languages
```

The blueprint stays in the root after conversion and acts as the project's
language topology manifest.

---

## The formatter

```sh
bullang fmt              # rewrite all .bu files to canonical style
bullang fmt --dry-run    # show what would change, write nothing
bullang check            # validate + type-check + report formatting drift
```

Canonical rules: 4-space pipe indentation, colon-aligned struct fields,
directives in order (#rank → #lang → #lib), one blank line between
functions. Escape block contents are never reformatted.

---

## CLI reference

| Command                                     | What it does                                             |
|---------------------------------------------|----------------------------------------------------------|
| `bullang init <name>`                       | Scaffold a new project (depth 2 by default)              |
| `bullang init <name> --depth N`             | Scaffold with a custom hierarchy depth (1–6)             |
| `bullang init <name> --lang <ext>`          | Set the target language at init time                     |
| `bullang init <name> --blueprint <file>`    | Init from a blueprint file                               |
| `bullang convert <folder>`                  | Transpile (reads #lang from inventory, default: rs)      |
| `bullang convert <folder> -e rs`            | Override target language                                 |
| `bullang convert file.bu`                   | Transpile a single file — output written next to source  |
| `bullang convert file.bu -o out.rs`         | Transpile a single file to an explicit path              |
| `bullang prod <folder>`                     | Strip test_ folders and work_division.md for production  |
| `bullang fmt`                               | Format all .bu files to canonical style                  |
| `bullang fmt --dry-run`                     | Show what would change without writing                   |
| `bullang check`                             | Validate, type-check, and verify formatting              |
| `bullang stdlib --list`                     | List all builtin functions with signatures               |
| `bullang update`                            | Pull and reinstall from main branch                      |
| `bullang update --experimental`             | Pull and reinstall from experimental branch              |
| `bullang lsp`                               | Start the LSP server                                     |
| `bullang editor-setup`                      | Write LSP config for Neovim / Helix / Emacs              |
| `bullang install`                           | Install bullang to system PATH                           |

---

## Typical workflow

```sh
# 1. Create a project
bullang init my_project --depth 3 --lang rs

# 2. Define structs in inventory.bu files (child structs before parent structs)

# 3. Write function bodies in .bu source files

# 4. Validate and check formatting
bullang check

# 5. Format if needed
bullang fmt

# 6. Convert — this README is deleted automatically
bullang convert my_project

# 7. Compile or run
cd _my_project && cargo build
```

---

*Source: https://github.com/My-sidequests/Bullang*

"#
}
